config/routes.rb
Rails.application.routes.draw do

  # ATENCAO SE COLOCAR resources ele SÓ FUNCIONA ROTAS RESTful 
 
  devise_for :users
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login',    to: 'devise/sessions#new', as: :login
    get 'logout',   to: 'devise/sessions#destroy', as: :logout
  end	
  
  root 'welcome#index'


  get 'home/index'
  get 'home/sobre'
  

  get 'html/index'

  get 'github/index'



  get 'ruby/index'
  get 'ruby/aplicacoes'
  get 'ruby/gems'
  get 'ruby/estilos'
  get 'ruby/dragonfly'
  get 'ruby/organograma'
  get 'ruby/testes'
  get 'ruby/active_record'
  get 'ruby/email'
  get 'ruby/deploy' 
  get 'ruby/mapas'
  get 'ruby/will_paginate'
  get 'ruby/nested'
##############################################################
# Aplicacao xingaAi
#


  resources :posts do 
    member do
    get "like", to: "posts#upvote"
    get "dislike", to: "posts#downvote"
    end
      
  	resources :comments , dependent: :destroy do
      member do
        patch :complete
     end
    end

      end



end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base

	#dragonfly_accessor :image
	# <%= image_tag post.image.thumb('400x200#').url , class: "thumbnail" if post.image_stored? %>
	# <%= f.file_field :image %>
	# <%= image_tag @post.image.thumb('400x200#').url , class: "thumbnail" if @post.image_stored? %>


	acts_as_votable

	belongs_to :user
	has_many :comments

	


	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :posts
   has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  
	protected
			def configure_permitted_parameters
			devise_parameter_sanitizer.for(:sign_up) << :name
			devise_parameter_sanitizer.for(:account_update) << :name


  end



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	# Normalmente teria index show edit mas aqui so havera create e destroy
	before_action :authenticate_user!

	

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new(comment_params)
		@comment.user_id = current_user.id if current_user
		# @comment.post_id = @post.id
		if @comment.save
		redirect_to post_path(@post)
		else
		render 'new'
		end
	end

	
	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
			redirect_to post_path(@post)
	end

	private
		def comment_params 
		params.require(:comment).permit(:body)
		end






end

app/controllers/github_controller.rb
class GithubController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def sobre
  end

  


end

app/controllers/html_controller.rb
class HtmlController < ApplicationController
	def index

	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController



	before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index,:show]

 
	def index
		@posts = Post.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
		@comments = Comment.all
		@comment = Comment.where(post_id: @post)
		# se quiser selecionar somente post do usuario
			# @posts = Post.where(user_id: current_user)

		@feito = Post.where(done: true)
		@aberto = Post.where(done: false)

	end



	def show
		@comments = Comment.where(post_id: @post).order("created_at DESC")
		@random_post = Post.where.not(id: @post).order("RANDOM()").first
	
	end

	def complete
		@post = Post.find(params[:id])
		@post.update_attribute(:completed_at , Time.now)
		redirect_to @post, notice: "Completed"
	end



	def new
		@post = current_user.posts.new
	end

	def create
		@post = current_user.posts.new(post_params)
		if @post.save
			redirect_to @post, notice: "Created Successfully"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post, notice: "Updated Successfully"
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to posts_path, notice: "Deleted"
	end


	def upvote
		@post.upvote_by current_user
		redirect_to :back
	end
	
	def downvote
		@post.downvote_by current_user
		redirect_to :back
	end
					


	private

	def find_post
		@post = Post.find(params[:id])

	end

	def post_params
		params.require(:post).permit(:title, :description, :done, :image)
	end





end

app/controllers/ruby_controller.rb
class RubyController < ApplicationController
	def index
	end

	def aplicacoes
	end

	def active_record
	end
	def deploy
	end

	def dragonfly
	end

	def estilos
	end

	def gems
	end	

	def mapas
	end

	def will_paginate
	end

	def nested
	end
	

	



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flass_class(msg)
		case msg
		when :success then "success"
		when :error   then "error"
		when :alert then "warning"
		when :notice then " "
		else "info"
		end
	end



end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/github_helper.rb
module GithubHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/html_helper.rb
module HtmlHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ruby_helper.rb
module RubyHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<div class="container">


<%= render partial: 'layouts/navbar' %>


<%= link_to 'Sobre', home_sobre_path , class: "btn btn-danger" %>

<hr>
<h1>Hello: Aqui fica a relação de materias</h1>

app/views/home/sobre.html.erb
<div class="container">

<%= render partial: 'layouts/navbar' %>

<div class="well">
<h1>Sobre</h1>
<h4>Aqui podera ficar informacoes sobre alunos ou detalhes afins...</h4>
</div>


	<%= link_to 'Voltar', home_index_path, class: "btn btn-default" %>


	</div>

app/views/html/index.html.erb
<%= render partial: 'layouts/navbar' %>

<div class="well">
<h1>Bem vindo ao mundo - HTML</h1>
<h4>Html - HyperText Mark Language é uma linguagem de texto que define a base da programacao</h4>
</div>

app/views/posts/index.html.erb
<div class="container">

<nav class="navbar navbar-default" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="/posts">POST'S</a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav">
		</ul>
		
		<ul class="nav navbar-nav navbar-right">
		<% if user_signed_in? %>
			<li>
			<%= link_to current_user.name , edit_user_registration_path %>
			</li>
			<li>
			<%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
			</li>
		<% else %>
			<li>
			 <%= link_to 'Sign Up', new_user_registration_path %>
			</li>
			<li>
			<%= link_to 'Log In', new_user_session_path %>
			</li>

			<% end %>
			
		</ul>
	</div><!-- /.navbar-collapse -->
</nav>

<%= link_to 'Voltar Monkey', home_index_path, class: "btn btn-primary" %>
<h1>Index Post</h1>



<%= link_to 'New Post', new_post_path, class: "btn btn-primary" %>

<hr>





<h3>Total de Posts | <%= @posts.count %></h3>
<h3>Total de Comentarios | <%= @comments.count %></h3>
<!-- 
 <nav>
  <ul class="pager">
    <li><a href="#">Previous</a></li>
    	<li><%= will_paginate @posts %></li>
    <li><a href="#">Next</a></li>
  </ul>
</nav> -->
 
<hr>
 <div id="posts" class="transitions-enabled infinite-scroll clearfix">
	<% @posts.each do |post| %>
		<div class="col-xs-8  col-sm-4 col-md-8">
		<div class="box panel panel-default" checked="checked">
		<div al>
		<div id="head">
		
		<!-- ajax -->
			
				<h3 align="center"><%= link_to post.title , post %></h3>
		</div>
			<p class="text-center"><%= time_ago_in_words(post.created_at) %></p>
			<p class="text-center"><%= post.user.name %></p>
			<p class="text-center"><%= post.comments.count %> comentarios</p>
	 		
	 		
	  </div>
   </div>
</div>

<% end %>	
</div>

<br>
<hr>


<div class="well">

<%= will_paginate @posts %>
</div> 




<script type="text/javascript">

$(document).ready(function() {
    if ($('.pagination').length) {
      $(window).scroll(function() {
        var url = $('.pagination .next_page').attr('href');
        if (url && $(window).scrollTop() > $(document).height() - $(window).height() - 50) {
          $('.pagination').text("Please Wait...");
          return $.getScript(url);
        }
      });
      return $(window).scroll();
    }
  });
  </script>

app/views/posts/show.html.erb
<div class="container">



<h1><%= @post.title %></h1>
<% if @post.done == true %>
		<h3 class="concluido">Post Concluido</h3>
	<% end %>

<h3><%= @post.description %></h3>
<h3><%= @post.user.email %></h3>
<h3><%= @post.done %></h3>
<hr>

<% if current_user = @post.user_id %>
	<%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are You Sure?" }, class: "btn btn-danger" %>
	<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default" %>

	
	

	<% end %>

<%= link_to 'Back', posts_path , class: "btn btn-default" %>

<hr>
	<h3>Opiniao Like/Dislike</h3>
	<div class="btn group">
			
			<%= link_to like_post_path(@post), method: :get, class: "btn btn-default" do %>
			<span class="fa fa-thumbs-o-up"> Like</span>
			<%= @post.get_upvotes.size %>
			<% end %>

			<%= link_to dislike_post_path(@post), method: :get, class: "btn btn-default" do %>
			<span class="fa fa-thumbs-o-down"> DisLike</span>
			<%= @post.get_downvotes.size %>
			<% end %>
	</div>

 <hr>



<h3>Random Post - Inspire-se</h3>

<div class="well col-md-4">
	<h5><%= link_to @random_post.title, post_path(@random_post) %></h5>
	<p>Shared by: <%= @random_post.user.name %></p>
	

</div>



	
	<div class="col-md-12">
	<h3>Adicionar Comentarios</h3>
	<%= render 'comments/form' %>
	<hr>


<h3>Veja Comentarios</h3>
<h3><%= pluralize(@post.comments.count, "Comment") %></h3>


<% @comments.each do |comment| %>
	<p> <%= comment.body %></p>

	<% if current_user == comment.user %>
	<p><%= comment.user.name %> </p>
	
	<%= link_to 'Delete Comment',[ @post, comment], method: :delete, data: { confirm: "Are You Sure?" }, class: "btn btn-danger btn-sm" %>
	<% end %>
	<hr>
<% end %>







</div>

app/views/ruby/active_record.html.erb
<div class="container">

<%= render partial: 'layouts/navbar' %>
<%= link_to 'Voltar', ruby_index_path, class: "btn btn-default" %>

<h1>Active Record</h1>
	<h3>Build and manage data</h3>
	<h3>Store Data & Retrieve</h3>

	<p>TED - Too early to Design -> Planejar Bem o que será feito com as informacoes - Reserve espaços para o futuro. Ex.Botão que ainda nao tem só futuro.</p>


<hr>

	<h1>Update Attributes:  eu nao gostei prefiro scope</h3>
	<div class="well">
		<p>def index <Br>
			@todos = Todo.where(done:  false) <br>
			@todone = Todo.where(done: true)</br>
		</p>
		<p> < %= link_to 'Mark as Done', todo_path(f), method: :put</p>

		<h3>update_attributes</h3>
		<p>Fazendo ex. modelo Todo</p>

		<p>Adicionar completed_at:datetime para monitorar , não esquecer deve haver também um boolean</p>
		<p>resources posts do<br>
			<code>member do <br>
				patch :complete</code><br>
		end</p>

		<p><kbd>controller:</kbd></p>
		<p>def <code>complete</code> <br>
			@posts = Post.find(params[:id]) <br>
			@post.<code>update_attributes("completed_at , Time.now")</code><br>
			redirect_to @posts_path, notice: "Post Completo"<Br>
			end </p>

			<p><kbd>view:</kbd></p>
			<p>< % if post.<code>completed_at.blank?</code> %>  ---> obs: pode criar no model um methodo</p>
			<p>< % if post.<code>realizado?</code></p> <br>
			<p>< % link_to 'Mark as Complete', realizado_posts_path(post), <code>method: :patch</code></p>
			<p>< % end %></p>


			<p>Obs: no model def realizado? <br> !completed_at.blank? <br> end</p>


	</div>

	
	<h1>Scope  --> Alvo</h1>
	<h3>Ajuda a manter o Model limpo para o user interface</h3>

	<div class="well">
	<p><kbd>Model:</kbd></p>
		<p>Exemplos:</p>
		<p>scope :premier, -> { where("employee <= ?", 30) }</p>
		<p>scope :newest,  -> { order("created_at DESC") }</p>
		<p>scope :starts_with, ->(letter) { where("name LIKE ?", letter + "%") }</p>
		<p>scope :nome, -> { where(first_name: "Hampton") }</p>

		<p><kbd>View:</kbd></p>
		<p>< %= @customers.<code>premier</code>.each do |c| %></p>
		<p>< %= @customers.<code>premier.starts_with("Ham")</code>.first do |c| %></p>


	</div>

	<h1>Query Inteface</h1>
		<div class="well">
			<p> employee.find(20)</p>
			<p>Ex. employee.<code>where</code>("name = ?", "Hampton")</p>
			<p>outros SQLs</p>
			<p>("name = ? OR age = ?", "Hampton", 30)</p>
			<p>.order("id ASC").count ou .limit(1)   ou .limit(5).offset(5)</p>

			<p>Avançados</p>
				<p>customer.find_each { |x| nil }</p>

			<H4>Eager - Loading -> nao executa toda a busca faz um PRE-load + rapido</H4>

			<p>customer.each { |customer| puts customer.time_entries.<code>inspect</code> } </p>
			
			<h3>Atualizando campos no rails console</h3>
			<p>Post.all.each { |f| f.update_attributes(state: "submitted") }</p>



		</div>


		<h1>FILTERS --> Selecionando por categoria</h1>
			<h3>Exemplo JOB BOARD</h3>

		<div class="well">
		<H4>1 - Criar category </H4>
			<p>rails g scaffold category  name:string</p>
			<p>2 - add_category_id_to_jobs  <code>category_id:integer</code></p>
			<p>3- Criar associações Model</p>
			<p>4- Strong Params - :category_id</p>
			<p>Obs: para sair cod 1,2,3 e colocar nome  fazer: Ex. cidade.estado_id para cidade.estado.name</p>

		<p><kbd>_form</kbd></p>
			<p><code>< % f.collection_select :category_id, Category.all, :id, :name, { include_blank: true  ou prompt: "Choose your category" }</code> %></p>

			<p>No header ou layouts/application ou _cabecalho(partial:)</p>

					<p>< %=<code>Category.all</code>.each do |category| %></p>
					<p>< %= link_to category.name , pagina_path(category:  category.name)</p>
					<p>< % end %></p>

		<p><kbd>Jobs controller</kbd></p>
		<p>def index <br>
				@categories = Category.all<br>
			   if params[:category].blank?  <br>
					@jobs = Job.all   <br>
			else  <br>
					@category_id = Category<code>.find_by</code>(name: params[:category]).id  <br>
					@jobs = Job.where(category_id: @category_id).order("created_at DESC") <br>
				end <br>
			end
			</p>
		</div>


		<h1>Validates para User</h1>
	<div class="well">
			<p>presence :true</p>
			<p>validates :username, length: { in: 3..15 }</p>
			<p>validates :country, inclusion: ['us', 'ca', 'uk']</p>
			<p>validates :name, exclusion: ['FDP']</p>
			<p>validates :score, numericality:  true</p>
			<p>validates :username, format: { with: /^[\w]$/} , message: "Username only letters and no ... space"</p>
	</div>


	<h3>Validando Email</h3>
		<div class="well">
		<p>validates :profile_name, presence: true, <br>
                           uniqueness: true,		<br>
                           format:  {						<br>
                             with: /[a-ZA-Z0-9_-]+/,<br>
                           }										<br>
    </p>
		</div>





		<h1>CallBacks</h1>
			<p>Constroi no Model um comportamento que será executado quando solicitado</p>
			<p>Sempre que vc trigger --> create,update,edit,destroy</p>

		<div class="well">
			<p><code>before_</code>create</code></p>
			<p><code>before_validation</code></p>
			<p>after_validation</p>
			<p>after_save</p>
			<p>around_save --> antes e depois</p></Br>
			<p>after_create</p>
			<p>around_create</p>
		

			<h3>Exemplo com User</h3>
				<p>validates :presence true, length: { in 4..100 } <br>
					before_validation :ensure_exists  <Br>
					before_validation :downcase_name <Br>
				</p>
				<p><strong>protected</strong></p>
				<p>def ensure_exists <br>
					 self.password ||= SecureRandom.urlsafe_base64  <Br>
					 end
				</p>
				<p> def downcase_name <Br>
				   self.name = self.name.downcase<Br>
				  end
				 </p>




		</div>




app/views/ruby/deploy.html.erb
<div class="container">

<%= render partial: 'layouts/navbar' %>
<%= link_to 'Voltar', ruby_index_path, class: "btn btn-default" %>

<h1>Deploy</h1>
<hr>

	<h3>Readme.md (markdown)</h3>
		<div class="well">
			<p>LEIAME<BR>
			===========================================<br>
			<strong>### Linha Bold</strong><br>
			<strong>></strong> blockquote com barra lateral<br>
			** palavra fica bold ** <br>
			http://monkeyschool.heroku.com  <br>
			* italico *  <br>
			' puts "Hello World"  '
		</div>


		<h1>heroku</h1>

		<h3>Pre Configuracao</h3>
					<p>production.rb  --> config.assets.compile = true</p>
					<p>Routes configuradas</p>
					<p>group :production do <Br>
							gem 'pg'<br>
							gem 'rails_12factor'<br>
						end</br>

						group :development do <br>
							gem 'sqlite3'  <br>
							end <br>

							<code>No final:</code>
							<p>ruby "2.0.0"</p>
					</p>


					<p>
			<p>OBS: caso precise gerar chave</p>
			<p>ssh-keygen -T rsa -C "email"</p>
			<p>R. ver success & http: resultado</p>
			<div class="well">
				<kbd>prompt:</kbd>
				<p>bundle install para gems</p>
				<p><kbd>Github subir</kbd></p>

				<p>heroku keys:add</p>
				<p>heroku login</p>
				<p>heroku create <strong>nome_aplicacao</strong></p>

				<p>git push heroku master  --> ver: git push -U master</p>
				<p>heroku run rake db:migrate</p>
				<p>heroku ps:scale web=1</p>
				<p>Obs: 1 Faixa do B.D gratuito</p>
			</div>




			<h1>Jackson P</h1>
			<h3>Heroku Linode e DigitalOcean</h3>
				<div class="well">
				
						<p>Caso nao funcione</p>
						<p> gem 'unicorn' no :production</p>
						<p>bundle</p>
						<p>criar config/unicorn.rb e colar texto </p>
						<p>criar arq Procfile /raiz</p>
			</div>



				<h3>Atualizar</h3>
				<p>git push heroku master</p>

app/views/ruby/email.html.erb
<div class="container">

<%= render partial: 'layouts/navbar' %>
<%= link_to 'Voltar', ruby_index_path, class: "btn btn-default" %>

<h1>E-Mail:</h1>
<hr>

<h3>Simples:</h3>
<p>< a href="mailto:kelber@gmail.com">Email</p>

app/views/ruby/index.html.erb
<div class="container">


<%= render partial: 'layouts/navbar' %>

<div class="well">
<h1>Bem vindo ao Ruby on Rails</h1>
<h4>Tudo sobre Ruby e Rails o framework ruby</h4>
</div>


	<%= link_to 'Voltar', home_index_path, class: "btn btn-default" %>

</div>

	<hr>
	<h1><%= link_to 'Gems', ruby_gems_path , class: "btn btn-primary" %></h1>
	<h1><%= link_to 'Estilos Css & Scss', ruby_estilos_path , class: "btn btn-primary" %></h1>
	<h1><%= link_to 'DragonFly Gem', ruby_dragonfly_path , class: "btn btn-danger" %></h1>

		<hr>
	<h3><%= link_to 'Nested', ruby_nested_path %></h3>
	<h3><%= link_to 'Organograma e Rotas RESTful', ruby_organograma_path %></h3>
	<h3><%= link_to 'TESTES', ruby_testes_path %></h3>


	<h3><%= link_to 'Email', ruby_email_path %></h3>
	<h3><%= link_to 'Active Records', ruby_active_record_path %></h3>
	<h3><%= link_to 'Mapas', ruby_mapas_path %></h3>
	<h3><%= link_to 'Deploy', ruby_deploy_path %></h3>

	<h3><%= link_to 'Will Paginate', ruby_will_paginate_path %></h3>





<hr>



<h3>Dica: rails g simple_form:install --bootstrap</h3>
<p>Ler arquivo initializers/simple_form === manual</p>
	<div class="well">
	<p><code>f.error_notification</code></p>
	<p>f.input :price, hint: "price in USD aparece embaixo do campo"</p>
	<p>f.input :release, label: "Data de Lancamento"</p>
	<p>f.association :categories, as: :check_boxes</p>
	<p>f.input :rating, collection: 1..5, as: :radio_buttons </p>
	<h4>Validations</h4>




	</div>

<h3>@posts.each<code>_slice(3) ?? o que faz? </code></h3>

<h3>Dica: Pluralize</h3>
<p>< % = pluralize(@posts.errors.count, "error") %></p>

<p>Dica: post.created_at.strftime("%B, %d, %Y)  %></p>

<p>Dica: LOGOTIPO < %= link_to image_tag('logo.svg'), root_path, id: "logo" %></p>

<p>DATAS:  invoice.date.strftime("%d/%m/%Y") fica: 9/12/2014 ou ("%d-%m%Y") fica: 9-12-2014</p>

<p>Dica: salvar arquivos .as_json , .as_xml,  .as_yaml</p>

<h3>VALORES:  price:decimal  e view: number_to_currenty(price)</h3>
	<p>Arrumar price com duas casas:  <code>price:decimal{12,2}</code></p>
	<p>V-34  CALCULOS</p>
	<p>< %= running_total = 0 %></p>
	<p>< %= @loop do purchases %> </p>
	<p>< %= purchase.quantity %></p>
	<p>< %= purchase.price  %></p>
	<p>< %= number(purchase.quantity * purchase.price  ) %></p>

	<p>< % running_total = running_total + (purchase.quantity * purchase.price  ) %></p>

	<h5>rever isto</h5>




	<hr>
<p> DICA:  INTE4POLACAO -  " #{post.title}  -  #{post.user_id} "  </p>
<h3>HELPERS</h3>
<P>def pegar_sexo(sex - este aqui é o campo db)  <br>
	if sex == 'M'  <Br>
	 'Masculino'  <br>
	else   			<Br>
		'Feminino'  <br>
  end <br>

 </p>
 <p>Na view: -->  <code># { pegar_sexo(post.sex) }</code></p>
	
<h3>Routes - Design Url's</h3>
<div class="well">
		<h3>Para Devise</h3>
		<p>devise_scope :user do <Br>
    get 'register', to: 'devise/registrations#new', as: :register <Br>
    get 'login',    to: 'devise/sessions#new', as: :login<br>
    get 'logout',   to: 'devise/sessions#destroy', as: :logout<br>
  end	<br>
  </p>
  <h1>OBS: Acho que nao esta funcionando.</h1>


  <h3>Rotas Normais</h3>
  <p>Ex:  /feed   ---->  get 'feed', to: 'path#index', as: :feed</p>

</div>


	<h1>Atualizacao de Attributos = completed</h1>

		<div class="well">


		<p>1 - Adicionar o campo completed_at </p>
		<p>rails g migration add_completed_at_post  completed_at:datetime</p>
		<p>2 - Arrumar route</p>
		<p>resources :posts do<br>
				member do <br>
				patch :complete    <Br>
				end  <br>
			end
			</p>

		</p>
		<p>3 - Adicionar campo ao view obs:verificar se vai mais de um id</p>
		<p>< %= link_to 'Mark Complete', complete_post_path(@post), method: :patch %></p>
		</div>


		<h1>Haml</h1>

	<div class="well">
			<p>Delay nao é problema do haml<br>
			remover as linhas 2 escrito turbolinks do cabecalho turbolinks = true</p>
			<p>Remover tambem do JS e gems</p>

			<p>no application(header)</p>
			<p>%link { rel: 'stylesheet', :href => 'http://googlefonts', type: 'text/css' }</p>
	</div>





<h1><code>Verificar</code> Flash.each para alerts</H1>

<div class="well">
		<p> < % flash.each do |name,msg| %><br>
		< %= content_tag(:div, msg, class: "alert alert-#{name}") % ><br>
		< % end % >
		</p>


		<h3>OU</h3>

		<p> < %= flash.each do |name, msg| %> <Br>
			= content_tag :div , msg, class: "alert alert-info"
			</p>

</div>
	
	
		<h1>Ex. aplicacao NoteNote</h1>
		<p>onde para entrar o usuario deve estar authenticado</p>

		<div class="well">
		<p><kbd>Routes - Usando dois roots</kbd></p>
		<p>
			root 'welcome#index'<br>
			
			authenticated :user do<br>
				root 'notes#index', as: 'authenticated_root'<br>
				end<br>
				// se usuario estiver authenticado o root será o notes#index
			</p>
		</div>


app/views/ruby/organograma.html.erb
<div class="container">

<%= render partial: 'layouts/navbar' %>
<%= link_to 'Voltar', ruby_index_path, class: "btn btn-default" %>
	<h1>MVC</h1>
	<hr>

	<H1> ROTAS --> CONTROLLER ----> VIEW<BR>
									MODEL vai/volta CONTROLLER<br>
									MODEL --> databases, api, rails app  <br>
	</h1>

	<H3>Verbos HTTP:</H3>
		<p>GET</p>
		<P>POST</P>
		<P>PUT</P>
		<P>DELETE</P>

		<p><code>Checar Lista  rake -T</code></p>